import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppContext } from '../context/AppContext';
import { RadialBarChart, RadialBar, PolarAngleAxis, ResponsiveContainer } from 'recharts';
import { FileDown, ArrowLeft, Lightbulb, Target, TrendingUp, AlertTriangle, BookOpen } from 'lucide-react';

export default function Report() {
  const navigate = useNavigate();
  const { state } = useAppContext();
  const [downloading, setDownloading] = useState(false);

  const lastAnswer = state.currentAnswers?.[state.currentAnswers.length - 1];

  useEffect(() => {
    if (!lastAnswer) {
      navigate('/modules');
    }
  }, [lastAnswer, navigate]);

  if (!lastAnswer) return null;

  const { moduleContent, scenario, attempts, finalScore } = lastAnswer;
  const optimalAttempt = attempts.find(a => a.consequence.isOptimal);
  const failedAttempts = attempts.filter(a => !a.consequence.isOptimal);

  const generatePDF = () => {
    setDownloading(true);
    try {
      // jsPDF is loaded globally via CDN in index.html
      const { jsPDF } = window.jspdf;
      const doc = new jsPDF();
      
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // Header
      doc.setFillColor(255, 107, 53); // Saffron
      doc.rect(0, 0, pageWidth, 40, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(24);
      doc.text("UdyamPath Executive Summary", 15, 25);
      
      // Meta data
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(12);
      doc.text(`Founder: ${state.user?.name || 'Startup Founder'}`, 15, 55);
      doc.text(`Startup Idea: ${state.idea.substring(0, 50)}...`, 15, 65);
      doc.text(`Module Completed: ${moduleContent.name}`, 15, 75);
      doc.text(`Final Diagnostic Score: ${finalScore}/100`, 15, 85);
      
      doc.setDrawColor(200, 200, 200);
      doc.line(15, 95, pageWidth - 15, 95);

      // Scenario Output
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(255, 107, 53);
      doc.text("The Challenge", 15, 110);
      
      doc.setTextColor(50, 50, 50);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      
      const splitScenario = doc.splitTextToSize(scenario.context, pageWidth - 30);
      doc.text(splitScenario, 15, 120);
      
      let cursorY = 120 + (splitScenario.length * 7) + 10;
      
      // The Golden Insight
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(15, 155, 88); // Green
      doc.text("The Proven Formula (Optimal Insight)", 15, cursorY);
      cursorY += 10;
      
      doc.setTextColor(50, 50, 50);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      const splitInsight = doc.splitTextToSize(optimalAttempt?.consequence.insight || '', pageWidth - 30);
      doc.text(splitInsight, 15, cursorY);
      cursorY += (splitInsight.length * 7) + 15;
      
      // Mistakes Matrix
      if (failedAttempts.length > 0) {
         doc.setFont("helvetica", "bold");
         doc.setFontSize(16);
         doc.setTextColor(233, 69, 96); // Red
         doc.text("Avoidable Mistakes (Trial & Error Trace)", 15, cursorY);
         cursorY += 10;
         
         failedAttempts.forEach((fa, i) => {
            if (cursorY > 260) {
               doc.addPage();
               cursorY = 20;
            }
            doc.setFont("helvetica", "bold");
            doc.setFontSize(11);
            doc.setTextColor(0, 0, 0);
            doc.text(`Misstep ${i+1}: ${fa.optionText}`, 15, cursorY);
            cursorY += 7;
            
            doc.setFont("helvetica", "italic");
            doc.setFontSize(10);
            doc.setTextColor(100, 100, 100);
            const fl = doc.splitTextToSize(`Consequence: ${fa.consequence.insight}`, pageWidth - 30);
            doc.text(fl, 15, cursorY);
            cursorY += (fl.length * 6) + 8;
         });
      }

      // Footer
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by UdyamPath AI - Built for Bharat", pageWidth/2, 290, { align: 'center' });

      doc.save(`UdyamPath_Report_${moduleContent.name.replace(/\\s+/g, '_')}.pdf`);
    } catch(err) {
      console.error(err);
      alert('Failed to generate PDF. Make sure jsPDF is loaded.');
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#1a1a2e] pt-24 pb-24 px-4 font-inter text-white">
      <div className="max-w-4xl mx-auto space-y-8 animate-slide-up">
         
         <div className="flex justify-between items-center bg-[#202f36] p-4 rounded-2xl border border-[#2b3e47] shadow-lg">
            <button onClick={() => navigate('/modules')} className="text-white/60 hover:text-[#FF6B35] flex items-center gap-2 font-bold px-4 py-2 transition-colors">
               <ArrowLeft className="w-5 h-5" /> Back to Modules
            </button>
            <button 
               onClick={generatePDF} 
               disabled={downloading}
               className="btn-primary flex items-center gap-2 px-6 py-2 shadow-[0_0_20px_rgba(255,107,53,0.3)] disabled:opacity-50"
            >
               <FileDown className="w-5 h-5"/>
               {downloading ? 'Compiling PDF...' : 'Download Full Report'}
            </button>
         </div>

         <div className="flex flex-col md:flex-row gap-8">
            {/* Score Ring */}
            <div className="w-full md:w-1/3 bg-[#16213e] p-8 rounded-3xl border border-white/10 flex flex-col items-center justify-center shadow-xl">
               <h3 className="font-poppins font-bold text-lg text-white/50 uppercase tracking-widest mb-4">Module Score</h3>
               <div className="w-48 h-48 relative mb-4">
                  <ResponsiveContainer width="100%" height="100%">
                     <RadialBarChart cx="50%" cy="50%" innerRadius="70%" outerRadius="100%" barSize={15} data={[{ name: 'Score', value: finalScore, fill: finalScore > 70 ? '#0f9b58' : finalScore > 40 ? '#FFD700' : '#e94560' }]} startAngle={90} endAngle={-270}>
                        <PolarAngleAxis type="number" domain={[0, 100]} angleAxisId={0} tick={false} />
                        <RadialBar background={{ fill: 'rgba(255,255,255,0.05)' }} clockWise dataKey="value" cornerRadius={10} animationDuration={1000} />
                     </RadialBarChart>
                  </ResponsiveContainer>
                  <div className="absolute inset-0 flex items-center justify-center flex-col">
                     <span className="font-poppins font-black text-5xl text-white">{finalScore}</span>
                  </div>
               </div>
               <p className="font-bold text-center text-white/80 leading-relaxed">
                  {finalScore === 100 ? "Flawless Execution! You immediately identified the optimal strategy." : `You found the right path after ${failedAttempts.length} missteps. Mistakes are the best teachers.`}
               </p>
            </div>

            {/* The Golden Insight / Success Review */}
            <div className="w-full md:w-2/3 flex flex-col gap-6">
               
               <div className="bg-[#f1ffde] border border-[#58cc02]/30 p-8 rounded-3xl shadow-[0_10px_40px_rgba(88,204,2,0.1)] relative overflow-hidden">
                  <div className="absolute top-0 right-0 w-32 h-32 bg-[#58cc02]/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2"></div>
                  <div className="flex items-center gap-3 mb-6 relative z-10">
                     <div className="p-3 bg-[#58cc02]/20 rounded-xl"><Lightbulb className="w-6 h-6 text-[#4da803]"/></div>
                     <h2 className="font-poppins font-black text-2xl text-[#4da803]">The Golden Formula</h2>
                  </div>
                  <p className="text-[#3b8502] text-lg font-medium leading-relaxed relative z-10">
                     {optimalAttempt?.consequence.insight}
                  </p>
               </div>

               {/* Mistake Trace Log */}
               {failedAttempts.length > 0 && (
                  <div className="bg-[#202f36] border border-[#2b3e47] p-8 rounded-3xl">
                     <div className="flex items-center gap-3 mb-6">
                        <div className="p-3 bg-white/5 rounded-xl"><AlertTriangle className="w-6 h-6 text-[#FFD700]"/></div>
                        <h2 className="font-poppins font-black text-xl text-white">Avoidable Pitfalls Traversed</h2>
                     </div>
                     <div className="space-y-6">
                        {failedAttempts.map((fa, i) => (
                           <div key={i} className="pl-4 border-l-2 border-[#e94560]/30 relative">
                              <div className="absolute -left-2 top-0 w-4 h-4 rounded-full bg-[#1a1a2e] border-2 border-[#e94560]"></div>
                              <h4 className="font-bold text-white mb-2 leading-relaxed">{fa.optionText}</h4>
                              <p className="text-[#e94560] text-sm bg-[#e94560]/5 p-3 rounded-xl border border-[#e94560]/10 leading-relaxed font-medium">
                                 {fa.consequence.insight}
                              </p>
                           </div>
                        ))}
                     </div>
                  </div>
               )}

            </div>
         </div>

      </div>
    </div>
  );
}