export const strings = {
  en: {
    startButton: 'Start My Journey',
    watchDemo: 'Watch Demo',
    analyzing: 'Analyzing your idea...',
    checking: 'Checking Indian market data...',
    preparing: 'Preparing your journey...',
    language: 'Language',
    idea: 'Idea',
    context: 'Context',
    profile: 'Profile',
    uniquenessScore: 'Uniqueness Score',
    feasibilityScore: 'Feasibility Score',
    targetAudience: 'Target Audience',
    marketSize: 'Market Size',
    existingSolutions: 'Existing Solutions',
    startSimulation: 'Start Your Simulation →',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    expert: 'Expert',
    generateScenario: 'Generating your scenario...',
    fetchNews: 'Fetching real-world news...',
    prepAudio: 'Preparing audio...',
    askGuru: '💬 Ask Udyam Guru',
    continue: 'Continue',
    check: 'Check',
    retry: 'Retry Connection',
    overallInsight: 'Overall Insight',
    strength: 'Your Strength',
    blindSpot: 'Blind Spot',
    readArticle: 'Read Full Article →',
    realWorldRef: 'Real World Reference',
    tryAgain: 'Try Again',
    anotherModule: 'Try Another Module',
    discussGuru: 'Discuss with Udyam Guru',
  },
  hi: {
    startButton: 'मेरी यात्रा शुरू करें',
    watchDemo: 'डेमो देखें',
    analyzing: 'आपके विचार का विश्लेषण हो रहा है...',
    checking: 'भारतीय बाजार डेटा की जाँच हो रही है...',
    preparing: 'आपकी यात्रा तैयार की जा रही है...',
    language: 'भाषा',
    idea: 'विचार',
    context: 'संदर्भ',
    profile: 'प्रोफ़ाइल',
    uniquenessScore: 'अद्वितीयता स्कोर',
    feasibilityScore: 'व्यवहार्यता स्कोर',
    targetAudience: 'लक्षित दर्शक',
    marketSize: 'बाजार का आकार',
    existingSolutions: 'मौजूदा समाधान',
    startSimulation: 'सिमुलेशन शुरू करें →',
    beginner: 'शुरुआती',
    intermediate: 'मध्यम',
    expert: 'विशेषज्ञ',
    generateScenario: 'आपका परिदृश्य तैयार किया जा रहा है...',
    fetchNews: 'वास्तविक दुनिया के समाचार प्राप्त किए जा रहे हैं...',
    prepAudio: 'ऑडियो तैयार किया जा रहा है...',
    askGuru: '💬 उद्यम गुरु से पूछें',
    continue: 'जारी रखें',
    check: 'जांचें',
    retry: 'पुनः प्रयास करें',
    overallInsight: 'समग्र जानकारी',
    strength: 'आपकी ताकत',
    blindSpot: 'कमजोरी',
    readArticle: 'पूरा लेख पढ़ें →',
    realWorldRef: 'वास्तविक दुनिया का संदर्भ',
    tryAgain: 'पुनः प्रयास करें',
    anotherModule: 'एक और मॉड्यूल आज़माएं',
    discussGuru: 'उद्यम गुरु के साथ चर्चा करें',
  },
  te: {
    startButton: 'నా ప్రయాణం ప్రారంభించండి',
    watchDemo: 'డెమో చూడండి',
    analyzing: 'మీ ఆలోచనను విశ్లేషిస్తున్నాము...',
    checking: 'భారతీయ మార్కెట్ డేటాను తనిఖీ చేస్తున్నాము...',
    preparing: 'మీ ప్రయాణాన్ని సిద్ధం చేస్తున్నాము...',
    language: 'భాష',
    idea: 'ఆలోచన',
    context: 'సందర్భం',
    profile: 'ప్రొఫైల్',
    uniquenessScore: 'ప్రత్యేకత స్కోర్',
    feasibilityScore: 'సాధ్యత స్కోర్',
    targetAudience: 'లక్ష్య ప్రేక్షకులు',
    marketSize: 'మార్కెట్ పరిమాణం',
    existingSolutions: 'ప్రస్తుత పరిష్కారాలు',
    startSimulation: 'మీ సిమ్యులేషన్ ప్రారంభించండి →',
    beginner: 'ప్రారంభకులకు',
    intermediate: 'మధ్యస్థం',
    expert: 'నిపుణుడు',
    generateScenario: 'మీ దృశ్యాన్ని రూపొందిస్తున్నాము...',
    fetchNews: 'నిజ ప్రపంచ వార్తలను పొందుతున్నాము...',
    prepAudio: 'ఆడియో సిద్ధం చేస్తున్నాము...',
    askGuru: '💬 ఉదయం గురుని అడగండి',
    continue: 'కొనసాగించు',
    check: 'తనిఖీ చేయండి',
    retry: 'మళ్లీ ప్రయత్నించండి',
    overallInsight: 'మొత్తం అంతర్దృష్టి',
    strength: 'మీ బలం',
    blindSpot: 'బ్లైండ్ స్పాట్',
    readArticle: 'పూర్తి కథనాన్ని చదవండి →',
    realWorldRef: 'నిజ ప్రపంచ సూచన',
    tryAgain: 'మళ్లీ ప్రయత్నించండి',
    anotherModule: 'మరొక మాడ్యూల్‌ని ప్రయత్నించండి',
    discussGuru: 'ఉదయం గురుతో చర్చించండి',
  },
  ta: {
    startButton: 'என் பயணத்தை தொடங்கு',
    watchDemo: 'செயல்முறை விளக்கம் காண்க',
    analyzing: 'உங்கள் யோசனையை பகுப்பாய்வு செய்கிறது...',
    checking: 'இந்திய சந்தை தரவை சரிபார்க்கிறது...',
    preparing: 'உங்கள் பயணத்தை தயார் செய்கிறது...',
    language: 'மொழி',
    idea: 'யோசனை',
    context: 'சூழல்',
    profile: 'சுயவிவரம்',
    uniquenessScore: 'தனிமை மதிப்பெண்',
    feasibilityScore: 'சாத்தியமான மதிப்பெண்',
    targetAudience: 'இலக்கு பார்வையாளர்கள்',
    marketSize: 'சந்தை அளவு',
    existingSolutions: 'தற்போதுள்ள தீர்வுகள்',
    startSimulation: 'உங்கள் உருவகப்படுத்துதலை தொடங்கவும் →',
    beginner: 'தொடக்கக்காரர்',
    intermediate: 'இடைநிலை',
    expert: 'நிபுணர்',
    generateScenario: 'உங்கள் சூழ்நிலையை உருவாக்குகிறது...',
    fetchNews: 'உண்மையான செய்திகளைப் பெறுகிறது...',
    prepAudio: 'ஆடியோ தயார்செய்கிறது...',
    askGuru: '💬 உத்யம் குருவிடம் கேள்',
    continue: 'தொடரவும்',
    check: 'சரிபார்க்க',
    retry: 'மீண்டும் முயற்சிக்கவும்',
    overallInsight: 'ஒட்டுமொத்த நுண்ணறிவு',
    strength: 'உங்கள் பலம்',
    blindSpot: 'தெரியாத இடம்',
    readArticle: 'முழு கட்டுரையை படிக்கவும் →',
    realWorldRef: 'உண்மையான உலக குறிப்பு',
    tryAgain: 'மீண்டும் முயற்சிக்கவும்',
    anotherModule: 'மற்றொரு தொகுதியை முயற்சிக்கவும்',
    discussGuru: 'உத்யம் குருவிடம் விவாதிக்கவும்',
  }
};
